
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '58560CFA078602B1DABFCB046E69E369'
    
_lr_action_items = {'HEADTAGS':([0,],[10,]),'PHONE':([0,],[1,]),'TITLE':([0,],[2,]),'SITES':([0,],[11,]),'BREAKS':([0,],[4,]),'HTMLTAGS':([0,],[3,]),'HEADING3':([0,],[12,]),'$end':([1,2,3,4,5,6,7,8,9,10,11,12,13,],[-11,-5,-1,-8,-10,-9,-6,-4,-2,-3,-7,-12,0,]),'HEADING1':([0,],[7,]),'PARATAGS':([0,],[8,]),'BODYTAGS':([0,],[9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'name':([0,],[5,]),'phone':([0,],[6,]),'start':([0,],[13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> HTMLTAGS','start',1,'p_start','PLYstarter.py',34),
  ('start -> BODYTAGS','start',1,'p_start','PLYstarter.py',35),
  ('start -> HEADTAGS','start',1,'p_start','PLYstarter.py',36),
  ('start -> PARATAGS','start',1,'p_start','PLYstarter.py',37),
  ('start -> TITLE','start',1,'p_start','PLYstarter.py',38),
  ('start -> HEADING1','start',1,'p_start','PLYstarter.py',39),
  ('start -> SITES','start',1,'p_start','PLYstarter.py',40),
  ('start -> BREAKS','start',1,'p_start','PLYstarter.py',41),
  ('start -> phone','start',1,'p_start','PLYstarter.py',42),
  ('start -> name','start',1,'p_start','PLYstarter.py',43),
  ('phone -> PHONE','phone',1,'p_phone','PLYstarter.py',51),
  ('name -> HEADING3','name',1,'p_name','PLYstarter.py',56),
]
